apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-service
  namespace: my-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-service
  template:
    metadata:
      labels:
        app: my-service
    spec:
      imagePullSecrets:
      - name: local-registry-secret
      containers:
      - name: my-service
        image: my-service.local:51337/my-service:v10
        imagePullPolicy: Always
        ports:
        - containerPort: 9000
        env:
        - name: ARGOCD_SERVER
          value: "argocd-server.argocd"
        - name: ARGOCD_PORT
          value: "443"
        volumeMounts:
        - name: hosts-volume
          mountPath: /etc/hosts
          subPath: hosts
      volumes:
      - name: hosts-volume
        configMap:
          name: hosts-config