apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: my-service

resources:
- namespace.yaml
- deployment.yaml
- service.yaml
- ingress.yaml
- registry-secret.yaml
- hosts-configmap.yaml 